# Generated by Django 4.2.16 on 2024-09-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_event_created_by_remove_volunteer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('P', 'Pending'), ('D', 'Declined')], default='P', max_length=1)),
                ('date_participated', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.volunteer')),
            ],
            options={
                'ordering': ['-date_participated'],
            },
        ),
    ]
